package com.hwua.erhai.entity;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.car_number
     *
     * @mbg.generated
     */
    private String carNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.brand_id
     *
     * @mbg.generated
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.model
     *
     * @mbg.generated
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.t_comments
     *
     * @mbg.generated
     */
    private String tComments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.price
     *
     * @mbg.generated
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.rent
     *
     * @mbg.generated
     */
    private Float rent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car.usable
     *
     * @mbg.generated
     */
    private Integer usable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.id
     *
     * @return the value of t_car.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.id
     *
     * @param id the value for t_car.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.car_number
     *
     * @return the value of t_car.car_number
     *
     * @mbg.generated
     */
    public String getCarNumber() {
        return carNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.car_number
     *
     * @param carNumber the value for t_car.car_number
     *
     * @mbg.generated
     */
    public void setCarNumber(String carNumber) {
        this.carNumber = carNumber == null ? null : carNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.brand_id
     *
     * @return the value of t_car.brand_id
     *
     * @mbg.generated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.brand_id
     *
     * @param brandId the value for t_car.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.model
     *
     * @return the value of t_car.model
     *
     * @mbg.generated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.model
     *
     * @param model the value for t_car.model
     *
     * @mbg.generated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.color
     *
     * @return the value of t_car.color
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.color
     *
     * @param color the value for t_car.color
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.category_id
     *
     * @return the value of t_car.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.category_id
     *
     * @param categoryId the value for t_car.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.t_comments
     *
     * @return the value of t_car.t_comments
     *
     * @mbg.generated
     */
    public String gettComments() {
        return tComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.t_comments
     *
     * @param tComments the value for t_car.t_comments
     *
     * @mbg.generated
     */
    public void settComments(String tComments) {
        this.tComments = tComments == null ? null : tComments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.price
     *
     * @return the value of t_car.price
     *
     * @mbg.generated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.price
     *
     * @param price the value for t_car.price
     *
     * @mbg.generated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.rent
     *
     * @return the value of t_car.rent
     *
     * @mbg.generated
     */
    public Float getRent() {
        return rent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.rent
     *
     * @param rent the value for t_car.rent
     *
     * @mbg.generated
     */
    public void setRent(Float rent) {
        this.rent = rent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.status
     *
     * @return the value of t_car.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.status
     *
     * @param status the value for t_car.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car.usable
     *
     * @return the value of t_car.usable
     *
     * @mbg.generated
     */
    public Integer getUsable() {
        return usable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car.usable
     *
     * @param usable the value for t_car.usable
     *
     * @mbg.generated
     */
    public void setUsable(Integer usable) {
        this.usable = usable;
    }
}