package com.hwua.erhai.entity;

import java.util.Date;

public class Record {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record.car_id
     *
     * @mbg.generated
     */
    private Integer carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record.start_date
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record.return_date
     *
     * @mbg.generated
     */
    private Date returnDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_record.payment
     *
     * @mbg.generated
     */
    private Float payment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record.id
     *
     * @return the value of t_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record.id
     *
     * @param id the value for t_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record.user_id
     *
     * @return the value of t_record.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record.user_id
     *
     * @param userId the value for t_record.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record.car_id
     *
     * @return the value of t_record.car_id
     *
     * @mbg.generated
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record.car_id
     *
     * @param carId the value for t_record.car_id
     *
     * @mbg.generated
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record.start_date
     *
     * @return the value of t_record.start_date
     *
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record.start_date
     *
     * @param startDate the value for t_record.start_date
     *
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record.return_date
     *
     * @return the value of t_record.return_date
     *
     * @mbg.generated
     */
    public Date getReturnDate() {
        return returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record.return_date
     *
     * @param returnDate the value for t_record.return_date
     *
     * @mbg.generated
     */
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_record.payment
     *
     * @return the value of t_record.payment
     *
     * @mbg.generated
     */
    public Float getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_record.payment
     *
     * @param payment the value for t_record.payment
     *
     * @mbg.generated
     */
    public void setPayment(Float payment) {
        this.payment = payment;
    }
}